Cleanup

diff --git a/.github/workflows/e2e_test.yaml b/.github/workflows/e2e_test.yaml
--- a/.github/workflows/e2e_test.yaml
+++ b/.github/workflows/e2e_test.yaml
@@ -148,35 +148,19 @@ jobs:
           # We dont need all content for the test, so create an orphan branch.
           git checkout --orphan ${{ steps.runner-name.outputs.name }}
           git reset
-          
-          WF_FILE=".github/workflows/schedule_test.yaml"
-          # Replace workflow event in schedule_test.yaml
+
+          WF_FILE=".github/workflows/schedule_issues_test.yaml"
+          # Replace workflow event in schedule_issues_test.yaml
           if [[ ${{ matrix.event.name }} == 'schedule' ]]; then
             sed -i "s/workflow_dispatch:/schedule:\n  - cron: '*\/5 * * * *'/" $WF_FILE
           else
-            sed -i "s/workflow_dispatch:/issues:\n  types: [opened]/" $WF_FILE
+            sed -i "s/workflow_dispatch:/issues:\n    types: [opened]/" $WF_FILE
           fi
           git add $WF_FILE
           git config user.name github-actions
           git config user.email github-actions@github.com
           git commit -m"Add ${{matrix.event.name}} workflow"
           git push origin ${{ steps.runner-name.outputs.name }}
-      - name: Create signed commit (Schedule)
-        if: matrix.event.name == 'schedule'
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          # The last commit on the branch is required to be signed in order to pass the repo policy check.
-          # We create an unused file and commit it using the GH API in order to create a signed commit.
-          # We need to use the GITHUB_TOKEN because the E2E_TESTING_TOKEN is user-bound and would 
-          # create an an unsigned commit.
-          CONTENT=$(echo "Hello world" | base64) 
-          gh api \
-            --method PUT \
-            /repos/${{ github.repository }}/contents/helloworld.txt \
-            --field message="Add schedule workflow" \
-            --field content="$CONTENT"  \
-            --field branch="${{ steps.runner-name.outputs.name }}"
       - name: Deploy github-runner Charm (Issues, Schedule)
         if: matrix.event.name == 'issues' || matrix.event.name == 'schedule'
         env:
@@ -328,24 +312,6 @@ jobs:
 
           TESTING_REPO=${{ secrets.E2E_TESTING_TOKEN_ORG }}/${{ steps.runner-name.outputs.name }}
 
-          # Create branch protection rule in order to be able to let schedule test pass repo policy check
-          gh api \
-            --method PUT \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${TESTING_REPO}/branches/main/protection \
-            -F required_status_checks=null \
-            -F enforce_admins=null \
-            -F required_pull_request_reviews=null \
-            -F restrictions=null
-
-          # Create signed commit protected branch in order to be able to let schedule test pass repo policy check
-          gh api \
-              --method POST \
-              -H "Accept: application/vnd.github+json" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              /repos/${TESTING_REPO}/branches/main/protection/required_signatures
-
           # For issues, we need to trigger the workflow by opening an issue
             if ${{ matrix.event.name == 'issues' }}; then
                 gh api \
@@ -355,7 +321,7 @@ jobs:
                 /repos/${TESTING_REPO}/issues \
                 -f title="Test issue ${{ steps.runner-name.outputs.name }}"
             fi
-          
+
           get-workflow-status() {
               # Search recent workflow runs for the one designated by the run-id ref
               output=$(gh run list \
@@ -395,12 +361,13 @@ jobs:
           conclusion=$(echo $runs | jq -r '.[0].conclusion')
           wf_run_id=$(echo $runs | jq -r '.[0].id')
 
+          logs_filename=${{matrix.event.name}}-workflow-logs.zip
           # We retrieve the logs because the testing repo is deleted at the end of the test
           gh api \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${TESTING_REPO}/actions/runs/${wf_run_id}/logs > schedule-workflow-logs.zip \
-              || (echo "Failed to retrieve logs from schedule tests" && rm schedule-workflow-logs.zip)
+            /repos/${TESTING_REPO}/actions/runs/${wf_run_id}/logs > ${logs_filename} \
+              || (echo "Failed to retrieve logs from schedule tests" && rm ${logs_filename})
 
 
           if [[ $status != "completed" || $conclusion != "success" ]]; then
@@ -411,12 +378,12 @@ jobs:
             echo "Workflow completed with status: $status, conclusion: $conclusion, run-id: ${{ steps.runner-name.outputs.name }}"
             kill $(jobs -p)
           fi
-      - name: Upload schedule test logs (Schedule)
-        if: always() && matrix.event.name == 'schedule'
+      - name: Upload test logs (Issues, Schedule)
+        if: always() && (matrix.event.name == 'issues' || matrix.event.name == 'schedule')
         uses: actions/upload-artifact@v3
         with:
-          name: schedule-workflow-logs.zip
-          path: schedule-workflow-logs.zip
+          name: ${{matrix.event.name}}-workflow-logs.zip
+          path: ${{matrix.event.name}}-workflow-logs.zip
           if-no-files-found: ignore
 
       - name: Show Firewall Rules
@@ -466,7 +433,7 @@ jobs:
     needs: [build-charm, run-id]
     runs-on: [self-hosted, linux, x64, "pr-${{ needs.run-id.outputs.run-id }}"]
     steps:
-      # Snapd can have some issues in privileged LXD containers without setting 
+      # Snapd can have some issues in privileged LXD containers without setting
       # security.nesting=True and this.
       - name: Fix snap issue in privileged LXD containers
         run: ln -s /bin/true /usr/local/bin/udevadm
