WIP integration test

diff --git a/.github/workflows/integration_tests.yaml b/.github/workflows/integration_tests.yaml
--- a/.github/workflows/integration_tests.yaml
+++ b/.github/workflows/integration_tests.yaml
@@ -4,102 +4,102 @@ on:
   push:
 
 jobs:
-  integration-test-charm-no-runner:
-    name: Integration test charm with no runner
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        juju: [3.1, 2.9]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup operator environment
-        uses: charmed-kubernetes/actions-operator@main
-        with:
-          juju-channel: ${{ matrix.juju }}/stable
-          provider: lxd
-      - name: Enable br_netfilter
-        run: sudo modprobe br_netfilter
-      - name: Run Integration tests
-        run: |
-          tox -e integration-juju${{ matrix.juju }} -- \
-            --keep-models \
-            --path ${{secrets.E2E_TESTING_REPO}} \
-            --token ${{secrets.E2E_TESTING_TOKEN}} \
-            --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
-            tests/integration/test_charm_no_runner.py
-  integration-test-charm:
-    name: Integration test charm
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        juju: [3.1, 2.9]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup operator environment
-        uses: charmed-kubernetes/actions-operator@main
-        with:
-          juju-channel: ${{ matrix.juju }}/stable
-          provider: lxd
-      - name: Enable br_netfilter
-        run: sudo modprobe br_netfilter
-      - name: Run Integration tests
-        run: |
-          tox -e integration-juju${{ matrix.juju }} -- \
-            --keep-models \
-            --path ${{secrets.E2E_TESTING_REPO}} \
-            --token ${{secrets.E2E_TESTING_TOKEN}} \
-            --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
-            tests/integration/test_charm.py
-  integration-test-charm-fork-repo:
-    name: Integration test charm with fork repo
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        juju: [3.1, 2.9]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup operator environment
-        uses: charmed-kubernetes/actions-operator@main
-        with:
-          juju-channel: ${{ matrix.juju }}/stable
-          provider: lxd
-      - name: Enable br_netfilter
-        run: sudo modprobe br_netfilter
-      - name: Run Integration tests
-        run: |
-          tox -e integration-juju${{ matrix.juju }} -- \
-            --keep-models \
-            --path ${{secrets.E2E_TESTING_REPO}} \
-            --token ${{secrets.E2E_TESTING_TOKEN}} \
-            --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
-            tests/integration/test_charm_fork_repo.py
-  integration-test-charm-scheduled-events:
-    name: Integration test charm scheduled events
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        juju: [3.1, 2.9]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup operator environment
-        uses: charmed-kubernetes/actions-operator@main
-        with:
-          juju-channel: ${{ matrix.juju }}/stable
-          provider: lxd
-      - name: Enable br_netfilter
-        run: sudo modprobe br_netfilter
-      - name: Run Integration tests
-        run: |
-          tox -e integration-juju${{ matrix.juju }} -- \
-            --keep-models \
-            --path ${{secrets.E2E_TESTING_REPO}} \
-            --token ${{secrets.E2E_TESTING_TOKEN}} \
-            --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
-            tests/integration/test_charm_scheduled_events.py
+#  integration-test-charm-no-runner:
+#    name: Integration test charm with no runner
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        juju: [3.1, 2.9]
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Setup operator environment
+#        uses: charmed-kubernetes/actions-operator@main
+#        with:
+#          juju-channel: ${{ matrix.juju }}/stable
+#          provider: lxd
+#      - name: Enable br_netfilter
+#        run: sudo modprobe br_netfilter
+#      - name: Run Integration tests
+#        run: |
+#          tox -e integration-juju${{ matrix.juju }} -- \
+#            --keep-models \
+#            --path ${{secrets.E2E_TESTING_REPO}} \
+#            --token ${{secrets.E2E_TESTING_TOKEN}} \
+#            --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
+#            tests/integration/test_charm_no_runner.py
+#  integration-test-charm:
+#    name: Integration test charm
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        juju: [3.1, 2.9]
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Setup operator environment
+#        uses: charmed-kubernetes/actions-operator@main
+#        with:
+#          juju-channel: ${{ matrix.juju }}/stable
+#          provider: lxd
+#      - name: Enable br_netfilter
+#        run: sudo modprobe br_netfilter
+#      - name: Run Integration tests
+#        run: |
+#          tox -e integration-juju${{ matrix.juju }} -- \
+#            --keep-models \
+#            --path ${{secrets.E2E_TESTING_REPO}} \
+#            --token ${{secrets.E2E_TESTING_TOKEN}} \
+#            --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
+#            tests/integration/test_charm.py
+#  integration-test-charm-fork-repo:
+#    name: Integration test charm with fork repo
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        juju: [3.1, 2.9]
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Setup operator environment
+#        uses: charmed-kubernetes/actions-operator@main
+#        with:
+#          juju-channel: ${{ matrix.juju }}/stable
+#          provider: lxd
+#      - name: Enable br_netfilter
+#        run: sudo modprobe br_netfilter
+#      - name: Run Integration tests
+#        run: |
+#          tox -e integration-juju${{ matrix.juju }} -- \
+#            --keep-models \
+#            --path ${{secrets.E2E_TESTING_REPO}} \
+#            --token ${{secrets.E2E_TESTING_TOKEN}} \
+#            --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
+#            tests/integration/test_charm_fork_repo.py
+#  integration-test-charm-scheduled-events:
+#    name: Integration test charm scheduled events
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        juju: [3.1, 2.9]
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Setup operator environment
+#        uses: charmed-kubernetes/actions-operator@main
+#        with:
+#          juju-channel: ${{ matrix.juju }}/stable
+#          provider: lxd
+#      - name: Enable br_netfilter
+#        run: sudo modprobe br_netfilter
+#      - name: Run Integration tests
+#        run: |
+#          tox -e integration-juju${{ matrix.juju }} -- \
+#            --keep-models \
+#            --path ${{secrets.E2E_TESTING_REPO}} \
+#            --token ${{secrets.E2E_TESTING_TOKEN}} \
+#            --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
+#            tests/integration/test_charm_scheduled_events.py
   integration-test-charm-metrics:
     name: Integration test charm metrics
     runs-on: ubuntu-latest
@@ -116,6 +116,10 @@ jobs:
           provider: lxd
       - name: Enable br_netfilter
         run: sudo modprobe br_netfilter
+      - name: Find available loop device
+        id: loop-device
+        run: |
+            sudo losetup -f >> $GITHUB_OUTPUT
       - name: Run Integration tests
         run: |
           tox -e integration-juju${{ matrix.juju }} -- \
@@ -123,22 +127,23 @@ jobs:
             --path ${{secrets.E2E_TESTING_REPO}} \
             --token ${{secrets.E2E_TESTING_TOKEN}} \
             --token-alt ${{secrets.E2E_TESTING_TOKEN_ALT}} \
+            --loop-device ${{ steps.loop-device.outputs.stdout }} \
             tests/integration/test_charm_metrics.py
-  required_status_checks:
-    name: Required Integration Test Status Checks
-    runs-on: ubuntu-latest
-    needs:
-      - integration-test-charm-no-runner
-      - integration-test-charm
-      - integration-test-charm-fork-repo
-      - integration-test-charm-scheduled-events
-      - integration-test-charm-metrics
-    if: always() && !cancelled()
-    timeout-minutes: 30
-    steps:
-      - run: |
-          [ '${{ needs.integration-test-charm-no-runner.result }}' = 'success' ] || (echo integration-test-charm-no-runner failed && false)
-          [ '${{ needs.integration-test-charm.result }}' = 'success' ] || (echo integration-test-charm failed && false)
-          [ '${{ needs.integration-test-charm-fork-repo.result }}' = 'success' ] || (echo integration-test-charm-fork-repo failed && false)
-          [ '${{ needs.integration-test-charm-scheduled-events.result }}' = 'success' ] || (echo integration-test-charm-schedule-events failed && false)
-          [ '${{ needs.integration-test-charm-metrics.result }}' = 'success' ] || (echo integration-test-charm-metrics failed && false)
+#  required_status_checks:
+#    name: Required Integration Test Status Checks
+#    runs-on: ubuntu-latest
+#    needs:
+#      - integration-test-charm-no-runner
+#      - integration-test-charm
+#      - integration-test-charm-fork-repo
+#      - integration-test-charm-scheduled-events
+#      - integration-test-charm-metrics
+#    if: always() && !cancelled()
+#    timeout-minutes: 30
+#    steps:
+#      - run: |
+#          [ '${{ needs.integration-test-charm-no-runner.result }}' = 'success' ] || (echo integration-test-charm-no-runner failed && false)
+#          [ '${{ needs.integration-test-charm.result }}' = 'success' ] || (echo integration-test-charm failed && false)
+#          [ '${{ needs.integration-test-charm-fork-repo.result }}' = 'success' ] || (echo integration-test-charm-fork-repo failed && false)
+#          [ '${{ needs.integration-test-charm-scheduled-events.result }}' = 'success' ] || (echo integration-test-charm-schedule-events failed && false)
+#          [ '${{ needs.integration-test-charm-metrics.result }}' = 'success' ] || (echo integration-test-charm-metrics failed && false)
