add workflow_dispatch

diff --git a/.github/workflows/scheduled_e2e_test.yaml b/.github/workflows/scheduled_e2e_test.yaml
--- a/.github/workflows/scheduled_e2e_test.yaml
+++ b/.github/workflows/scheduled_e2e_test.yaml
@@ -4,7 +4,10 @@ name: Scheduled End-to-End Test
 # These test is for local LXD and is ran weekly.
 
 on:
-  pull_request:
+  schedule:
+    - cron: "15 4 * * 2"
+
+  workflow_dispatch:
 
 jobs:
   build-charm:
@@ -245,19 +248,12 @@ jobs:
           # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
           GH_TOKEN: ${{ matrix.event.name == 'workflow_dispatch' && secrets.GITHUB_TOKEN || secrets.E2E_TESTING_TOKEN }}
         run: |
-          # Base any future branches on the current branch
-          # We need to reference GITHUB_REF_NAME if this e2e_test workflow is scheduled
-          # otherwise use GITHUB_HEAD_REF for pull_request or push probably used for manual testing
-          if $GITHUB_EVENT_NAME == 'schedule'; then
-              REF_NAME=$GITHUB_REF_NAME
-          else
-              REF_NAME=$GITHUB_HEAD_REF
-          fi
+          # Base any future branches on the current branch.
           REF_SHA=$(gh api \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${{ secrets.E2E_TESTING_REPO }}/git/ref/heads/$REF_NAME \
-            --jq .object.sha) || (echo "Failed to get REF_SHA using $REF_NAME" && false)
+            /repos/${{ secrets.E2E_TESTING_REPO }}/git/ref/heads/$GITHUB_REF_NAME \
+            --jq .object.sha) || (echo "Failed to get REF_SHA using $GITHUB_REF_NAME" && false)
 
           # Create a temporary reference/branch
           # For push, this should trigger the "Push Event Tests" workflow automatically
