Update start_e2e_test.yaml

diff --git a/.github/workflows/start_e2e_test.yaml b/.github/workflows/start_e2e_test.yaml
--- a/.github/workflows/start_e2e_test.yaml
+++ b/.github/workflows/start_e2e_test.yaml
@@ -74,18 +74,6 @@ jobs:
     runs-on: [ self-hosted, linux, x64, e2e-test ]
     needs: [ build-charm, run-id ]
     steps:
-      - name: Install GitHub Cli
-        run: which gh || sudo apt install gh -y
-
-      - name: Watch github-runner
-        env:
-          GH_TOKEN: ${{ secrets.E2E_TESTING_TOKEN }}
-        run: |
-          gh api \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${{ secrets.E2E_TESTING_REPO }}/actions/runs/$GITHUB_RUN_ID/attempts/$GITHUB_RUN_ATTEMPT/jobs
-
       - name: Setup Lxd Juju Controller
         uses: charmed-kubernetes/actions-operator@main
         with:
@@ -126,15 +114,27 @@ jobs:
         run: which gh || sudo apt install gh -y
 
       - name: Watch github-runner
+        env:
+          GH_TOKEN: ${{ secrets.E2E_TESTING_TOKEN }}
         run: |
-          gh api \
+          juju debug-log --replay --tail &
+          
+          while :; do
+            JOBS=$(gh api \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${{ secrets.E2E_TESTING_REPO }}/actions/runs/$GITHUB_RUN_ID/attempts/$GITHUB_RUN_ATTEMPT/jobs
-
-          juju debug-log --replay --tail
-
-
+            /repos/${{ secrets.E2E_TESTING_REPO }}/actions/runs/$GITHUB_RUN_ID/attempts/$GITHUB_RUN_ATTEMPT/jobs)
+            CONCLUSION=$(echo $JOBS | jq -r '.jobs[] | select(.name == "End-to-End Test") | .conclusion')
+            STATUS=$(echo $JOBS | jq -r '.jobs[] | select(.name == "End-to-End Test") | .status')
+            if [[ $status != "queued" && $status != "in_progress" ]]; then
+              break
+            fi
+          done
+          if [[ $STATUS != "completed" || $CONCLUSION != "success" ]]; then
+            echo "test workflow failed with status: $STATUS, conclusion: $CONCLUSION"  
+            exit 1
+          fi
+ 
   e2e-test:
     name: End-to-End Test
     needs: [ build-charm, run-id ]
